# Site settings
title: Magic Bucket
email: team@magicbucket.fr
description: Magic Bucket est un collectif qui réunit 4 amoureux du web autour de projets interactifs funs et amusants.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://magicbucket.fr" # the base hostname & protocol for your site
twitter_username: MagicBucketTeam
github_username:  zhouzi

# Build settings
markdown: kramdown